[package]
name = "mavlink_proxy_server"
version = "0.1.0"
authors = ["John Hodge <tpg@ucc.asn.au>"]

[dependencies]
tokio-core = "0.1"
tokio-io = "0.1"
tokio-proto = "0.1"
futures = "0.1"
crc16 = "0.3"
log = "*"
env_logger = "0.4"
byteorder = "*"
