[package]
name = "loging_only_server"
version = "0.1.0"
authors = ["John Hodge <tpg@mutabah.net>"]

[dependencies]
byteorder = "1.0"
crc16 = "0.3"
log = "0.3"
env_logger = "0.4.3"
chrono = "0.4"
mavlink = "*"
